<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class UsersTableSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('users')->insert([
            // Admin - Keep this as the only admin
            [
                'first_name' => 'John',
                'middle_name' => 'van',
                'last_name' => 'Doe',
                'birth_date' => '1990-01-01',
                'username' => 'johndoe',
                'email' => 'john.doe@example.com',
                'phone' => '+31612345678',
                'password' => Hash::make('password123'),
                'is_logged_in' => false,
                'logged_in_at' => null,
                'logged_out_at' => null,
                'is_active' => true,
                'remark' => 'Administrator',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            
            // Instructors (5 total including Jane Smith)
            [
                'first_name' => 'Jane',
                'middle_name' => null,
                'last_name' => 'Smith',
                'birth_date' => '1995-05-15',
                'username' => 'janesmith',
                'email' => 'jane.smith@example.com',
                'phone' => '+31623456789',
                'password' => Hash::make('password123'),
                'is_logged_in' => false,
                'logged_in_at' => null,
                'logged_out_at' => null,
                'is_active' => true,
                'remark' => 'Senior Instructor',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'first_name' => 'Michael',
                'middle_name' => null,
                'last_name' => 'Brown',
                'birth_date' => '1988-07-22',
                'username' => 'michaelbrown',
                'email' => 'michael.brown@example.com',
                'phone' => '+31645678901',
                'password' => Hash::make('password123'),
                'is_logged_in' => false,
                'logged_in_at' => null,
                'logged_out_at' => null,
                'is_active' => true,
                'remark' => 'Instructor - Manual transmission specialist',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'first_name' => 'David',
                'middle_name' => 'van',
                'last_name' => 'Berg',
                'birth_date' => '1992-03-18',
                'username' => 'davidberg',
                'email' => 'david.berg@example.com',
                'phone' => '+31656789012',
                'password' => Hash::make('password123'),
                'is_logged_in' => false,
                'logged_in_at' => null,
                'logged_out_at' => null,
                'is_active' => true,
                'remark' => 'Instructor - Defensive driving specialist',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'first_name' => 'Laura',
                'middle_name' => null,
                'last_name' => 'Jansen',
                'birth_date' => '1990-11-30',
                'username' => 'laurajansen',
                'email' => 'laura.jansen@example.com',
                'phone' => '+31667890123',
                'password' => Hash::make('password123'),
                'is_logged_in' => false,
                'logged_in_at' => null,
                'logged_out_at' => null,
                'is_active' => true,
                'remark' => 'Instructor - Highway driving specialist',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'first_name' => 'Mohamed',
                'middle_name' => null,
                'last_name' => 'Ahmed',
                'birth_date' => '1985-08-12',
                'username' => 'mohamedahmed',
                'email' => 'mohamed.ahmed@example.com',
                'phone' => '+31678901234',
                'password' => Hash::make('password123'),
                'is_logged_in' => false,
                'logged_in_at' => null,
                'logged_out_at' => null,
                'is_active' => true,
                'remark' => 'Instructor - Urban driving specialist',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            
            // Students (15 total including Alice Johnson)
            [
                'first_name' => 'Alice',
                'middle_name' => null,
                'last_name' => 'Johnson',
                'birth_date' => '2000-09-10',
                'username' => 'alicejohnson',
                'email' => 'alice.johnson@example.com',
                'phone' => '+31634567890',
                'password' => Hash::make('studentpass'),
                'is_logged_in' => false,
                'logged_in_at' => null,
                'logged_out_at' => null,
                'is_active' => true,
                'remark' => 'Student - Fast learner',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'first_name' => 'Thomas',
                'middle_name' => null,
                'last_name' => 'Wilson',
                'birth_date' => '2001-05-14',
                'username' => 'thomaswilson',
                'email' => 'thomas.wilson@example.com',
                'phone' => '+31689012345',
                'password' => Hash::make('studentpass'),
                'is_logged_in' => false,
                'logged_in_at' => null,
                'logged_out_at' => null,
                'is_active' => true,
                'remark' => 'Student - Beginner',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'first_name' => 'Sara',
                'middle_name' => null,
                'last_name' => 'Vries',
                'birth_date' => '1999-02-28',
                'username' => 'saravries',
                'email' => 'sara.vries@example.com',
                'phone' => '+31690123456',
                'password' => Hash::make('studentpass'),
                'is_logged_in' => false,
                'logged_in_at' => null,
                'logged_out_at' => null,
                'is_active' => true,
                'remark' => 'Student - Some previous experience',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'first_name' => 'Lucas',
                'middle_name' => 'de',
                'last_name' => 'Groot',
                'birth_date' => '2002-07-19',
                'username' => 'lucasgroot',
                'email' => 'lucas.groot@example.com',
                'phone' => '+31701234567',
                'password' => Hash::make('studentpass'),
                'is_logged_in' => false,
                'logged_in_at' => null,
                'logged_out_at' => null,
                'is_active' => true,
                'remark' => 'Student - Complete beginner',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'first_name' => 'Emma',
                'middle_name' => null,
                'last_name' => 'Bakker',
                'birth_date' => '2001-11-03',
                'username' => 'emmabakker',
                'email' => 'emma.bakker@example.com',
                'phone' => '+31712345678',
                'password' => Hash::make('studentpass'),
                'is_logged_in' => false,
                'logged_in_at' => null,
                'logged_out_at' => null,
                'is_active' => true,
                'remark' => 'Student - Anxious driver',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'first_name' => 'Noah',
                'middle_name' => null,
                'last_name' => 'Peters',
                'birth_date' => '2000-04-22',
                'username' => 'noahpeters',
                'email' => 'noah.peters@example.com',
                'phone' => '+31723456789',
                'password' => Hash::make('studentpass'),
                'is_logged_in' => false,
                'logged_in_at' => null,
                'logged_out_at' => null,
                'is_active' => true,
                'remark' => 'Student - Quick learner',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'first_name' => 'Lotte',
                'middle_name' => null,
                'last_name' => 'Visser',
                'birth_date' => '2002-01-17',
                'username' => 'lottevisser',
                'email' => 'lotte.visser@example.com',
                'phone' => '+31734567890',
                'password' => Hash::make('studentpass'),
                'is_logged_in' => false,
                'logged_in_at' => null,
                'logged_out_at' => null,
                'is_active' => true,
                'remark' => 'Student - Nervous',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'first_name' => 'Daan',
                'middle_name' => 'van',
                'last_name' => 'Dijk',
                'birth_date' => '1999-08-09',
                'username' => 'daandijk',
                'email' => 'daan.dijk@example.com',
                'phone' => '+31745678901',
                'password' => Hash::make('studentpass'),
                'is_logged_in' => false,
                'logged_in_at' => null,
                'logged_out_at' => null,
                'is_active' => true,
                'remark' => 'Student - Confident',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'first_name' => 'Sophie',
                'middle_name' => null,
                'last_name' => 'Meijer',
                'birth_date' => '2002-12-05',
                'username' => 'sophiemeijer',
                'email' => 'sophie.meijer@example.com',
                'phone' => '+31756789012',
                'password' => Hash::make('studentpass'),
                'is_logged_in' => false,
                'logged_in_at' => null,
                'logged_out_at' => null,
                'is_active' => true,
                'remark' => 'Student - Cautious driver',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'first_name' => 'Tim',
                'middle_name' => null,
                'last_name' => 'Hendriks',
                'birth_date' => '2000-06-14',
                'username' => 'timhendriks',
                'email' => 'tim.hendriks@example.com',
                'phone' => '+31767890123',
                'password' => Hash::make('studentpass'),
                'is_logged_in' => false,
                'logged_in_at' => null,
                'logged_out_at' => null,
                'is_active' => true,
                'remark' => 'Student - Previous moped experience',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'first_name' => 'Julia',
                'middle_name' => null,
                'last_name' => 'Boer',
                'birth_date' => '2001-09-28',
                'username' => 'juliaboer',
                'email' => 'julia.boer@example.com',
                'phone' => '+31778901234',
                'password' => Hash::make('studentpass'),
                'is_logged_in' => false,
                'logged_in_at' => null,
                'logged_out_at' => null,
                'is_active' => true,
                'remark' => 'Student - Calm driver',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'first_name' => 'Max',
                'middle_name' => 'van der',
                'last_name' => 'Meer',
                'birth_date' => '2000-03-12',
                'username' => 'maxmeer',
                'email' => 'max.meer@example.com',
                'phone' => '+31789012345',
                'password' => Hash::make('studentpass'),
                'is_logged_in' => false,
                'logged_in_at' => null,
                'logged_out_at' => null,
                'is_active' => true,
                'remark' => 'Student - Aggressive tendencies',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'first_name' => 'Fleur',
                'middle_name' => null,
                'last_name' => 'Dijkstra',
                'birth_date' => '2001-02-18',
                'username' => 'fleurdijkstra',
                'email' => 'fleur.dijkstra@example.com',
                'phone' => '+31790123456',
                'password' => Hash::make('studentpass'),
                'is_logged_in' => false,
                'logged_in_at' => null,
                'logged_out_at' => null,
                'is_active' => true,
                'remark' => 'Student - Careful driver',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'first_name' => 'Sven',
                'middle_name' => null,
                'last_name' => 'Smit',
                'birth_date' => '2000-10-27',
                'username' => 'svensmit',
                'email' => 'sven.smit@example.com',
                'phone' => '+31801234567',
                'password' => Hash::make('studentpass'),
                'is_logged_in' => false,
                'logged_in_at' => null,
                'logged_out_at' => null,
                'is_active' => true,
                'remark' => 'Student - Technically skilled',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'first_name' => 'Isa',
                'middle_name' => null,
                'last_name' => 'Koning',
                'birth_date' => '2002-05-01',
                'username' => 'isakoning',
                'email' => 'isa.koning@example.com',
                'phone' => '+31812345678',
                'password' => Hash::make('studentpass'),
                'is_logged_in' => false,
                'logged_in_at' => null,
                'logged_out_at' => null,
                'is_active' => true,
                'remark' => 'Student - Eager to learn',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
